server:
  port: 8083
spring:
  application:
    name: api-gateway
  cloud:
    consul:
      discovery:
        health-check-path: /info
management:
  security:
    enabled: false

zuul:
  ignored-services: '*'
  routes:
    rating: /catalogue/**
    payment: /payment/**
    catalogue: /payment/**
    history: /history/**
    checkout: /checkout/**
    admin: /admin/**