server:
  port: 8083
spring:
  application:
    name: api-gateway
  cloud:
    consul:
      discovery:
        health-check-path: /info
  sleuth:
    web:
      skipPattern: (^watch.*|.*watch$|.*info$)
    sampler:
      percentage: 1.0

management:
  security:
    enabled: false

zuul:
  ignored-services: '*'
  routes:
    rating-service: /rating-service/**
    payment-service: /payment-service/**
    catalogue-service: /catalogue-service/**
    checkout-service: /checkout-service/**
