server:
  port: 8083

spring:
  application:
    name: api-gateway

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"

    prometheus:
      enabled: true


