server:
  port: 8083

spring:
  application:
    name: gateway
  cloud:
    consul:
      discovery:
        health-check-path: /info
  sleuth:
    web:
      skipPattern: (^watch.*|.*watch$|.*info$)
    sampler:
      percentage: 1.0

management:
  security:
    enabled: false

zuul:
  ignored-services: '*'
  routes:
    rating: /rating/**
    payment: /payment/**
    catalogue: /catalogue/**
    checkout: /checkout/**
    stock: /stock/**